name: metalearners
channels:
  - qc-internal
  - conda-forge
  - nodefaults
dependencies:
  ## Git
  - pre-commit
  - git_root
  ## Python
  - pip
  - python>=3.9
  - setuptools-scm
  - setuptools>=61 # Adds support for pyproject.toml package declaration.
  ## Documentation
  - make
  - numpydoc
  - sphinx
  - sphinxcontrib-apidoc
  - sphinx_rtd_theme
  ## Testing
  - pytest>=6 # Adds --import-mode option
  - pytest-cov
  ##  Numerical
  # First version to add the return_indices parameter to cross_validate.
  - scikit-learn>=1.3
  - numpy
  - pandas
  - typing-extensions
  - lightgbm
