name: Type check
on: [push]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: "bash -el {0}"

env:
  QUETZ_API_KEY: "${{ secrets.QUETZ_API_KEY }}"

jobs:
  mypy:
    name: Run Mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
          fetch-depth: 0
      - name: Set up Conda env
        uses: mamba-org/setup-micromamba@422500192359a097648154e8db4e39bdb6c6eed7
        with:
          condarc-file: .github/assets/.condarc
          environment-file: environment.yml
          cache-environment: true
      - name: Install repository
        run: >-
          python -m pip install --no-build-isolation --no-deps
          --disable-pip-version-check -e .
      - name: Run mypy
        run: mypy .
